[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/dev/search-taal-demo"
  to = "https://kumu.io/factorenmodel-dev/search-taal-demo"
  force = true

[[redirects]]
  from = "/dev/stevige-start-demo"
  to = "https://kumu.io/factorenmodel-dev/stevige-start-demo"
  force = true
  
